-- phpMyAdmin SQL Dump
-- version 4.5.0.2
-- http://www.phpmyadmin.net
--
-- Host: 127.0.0.1
-- Czas generowania: 10 Lut 2016, 21:14
-- Wersja serwera: 10.0.17-MariaDB
-- Wersja PHP: 5.6.14

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Baza danych: `olgaz`
--

-- --------------------------------------------------------

--
-- Struktura tabeli dla tabeli `category`
--

CREATE TABLE `category` (
  `id` int(11) NOT NULL,
  `name` varchar(266) NOT NULL,
  `is_active` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin2;

--
-- Zrzut danych tabeli `category`
--

INSERT INTO `category` (`id`, `name`, `is_active`) VALUES
(1, 'Ubranka', 1),
(2, 'Zabawki', 1),
(3, 'Wypieki', 1),
(5, 'sfdfd', 0);

-- --------------------------------------------------------

--
-- Struktura tabeli dla tabeli `comments`
--

CREATE TABLE `comments` (
  `id` int(11) NOT NULL,
  `content` text NOT NULL,
  `nick` varchar(50) DEFAULT NULL,
  `email` varchar(50) DEFAULT NULL,
  `data_creation` int(11) DEFAULT NULL,
  `last_modification` int(11) DEFAULT NULL,
  `is_active` int(11) NOT NULL,
  `post_id` int(5) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin2;

-- --------------------------------------------------------

--
-- Struktura tabeli dla tabeli `images`
--

CREATE TABLE `images` (
  `id` int(11) NOT NULL,
  `name` varchar(50) NOT NULL,
  `post_id` int(5) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin2;

-- --------------------------------------------------------

--
-- Struktura tabeli dla tabeli `post`
--

CREATE TABLE `post` (
  `id` int(11) NOT NULL,
  `title` varchar(255) DEFAULT NULL,
  `content` text,
  `short_content` varchar(255) DEFAULT NULL COMMENT 'Generowany automatycznie z opis',
  `user_id` int(11) DEFAULT NULL,
  `data_creation` int(11) DEFAULT NULL,
  `last_modification` int(11) DEFAULT NULL,
  `is_active` tinyint(1) DEFAULT NULL,
  `tags` varchar(255) DEFAULT NULL,
  `nice_link` varchar(256) DEFAULT NULL,
  `category_id` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin2;

--
-- Zrzut danych tabeli `post`
--

INSERT INTO `post` (`id`, `title`, `content`, `short_content`, `user_id`, `data_creation`, `last_modification`, `is_active`, `tags`, `nice_link`, `category_id`) VALUES
(1, 'Mariusza pierwszy wpis edytowalny', '<p>L<span style="color:#A52A2A"><strong>orem ipsum dolor sit amet, consecte</strong></span>tur adipiscing elit. Proin nulla urna, tincidunt eu porttitor nec, aliquam at libero. Aenean nisl lorem, interdum ac euismod nec, consequat ac nisi. Etiam laoreet auctor sollicitudin. Maecenas vitae convallis turpis. In hac habitasse platea dictumst. Donec a rhoncus lectus, sed blandit nulla. Nullam nec tempor dolor. Fusce pretium a quam et efficitur. Ut eget purus feugiat, dictum lectus nec, tristique turpis.<u><span style="background-color:#EE82EE"> Aliquam ornare tortor non ipsum facilisis</span></u> efficitur. Ut dolor magna, pulvinar sit amet erat et, eleifend laoreet nisl. Duis eget ligula eget ex interdum tincidunt. Nunc nec neque tincidunt ex maximus venenatis. Vestibulum imperdiet enim non efficitur interdum. Nullam non justo ac arcu ultrices condimentum eu at ipsum. Suspendisse aliquet tristique libero non fermentum. Suspendisse quis nisl malesuada, posuere turpis id, laoreet metus. Pellentesque eget aliquet justo, vitae fringilla erat. In sed risus maximus, facilisis neque sodales, consequat libero. Etiam convallis porttitor risus vitae hendrerit. Duis ac magna quis diam malesuada tempus et eu sem. Suspendisse tincidunt tempus diam, non euismod lorem fringilla at. Suspendisse pellentesque tincidunt pretium. Sed a arcu facilisis, blandit urna quis, suscipit arcu. Aliquam placerat nibh ipsum, non malesuada turpis vulputate quis. Fusce aliquam nulla et eros vulputate, eu vulputate ante commodo. Phasellus scelerisque mauris in viverra pharetra. Nulla facilisi. Donec dignissim aliquet rutrum. Sed tortor orci, tincidunt et feugiat quis, aliquet at mauris. Fusce pellentesque dui congue mauris elementum, a eleifend enim tincidunt. Duis sed nunc aliquet, mattis enim in, tincidunt dui. Proin sed mi viverra, semper velit eget, porta mauris. Sed sed purus odio. Vivamus eu sollicitudin nulla, ut tristique elit. Mauris fermentum varius malesuada. Praesent laoreet quam libero, in semper dolor placerat quis. Donec vitae enim congue neque viverra vulputate. Mauris sit amet massa eleifend, rutrum lorem viverra, tincidunt nisi. Nulla sed ultrices massa, ut blandit tellus. Sed suscipit consectetur interdum. Phasellus sit amet orci gravida, lacinia massa id, efficitur libero. Morbi nisl lorem, tincidunt eu est porta, bibendum posuere tortor.</p>\r\n', 'Proin nulla urna, tincidunt eu porttitor nec, aliquam at libero. Aenean nisl lorem, interdum ac euismod nec, consequat ac nisi. Etiam la', 1, 1449299283, 1453842412, 1, 'test, MS, mariuszs', 'mariusza-pierwszy-wpis-edytowalny', 1),
(3, 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit', 'Lorem Ipsum jest tekstem stosowanym jako przykładowy wypełniacz w przemyśle poligraficznym. Został po raz pierwszy użyty w XV w. przez nieznanego drukarza do wypełnienia tekstem próbnej książki. Pięć wieków później zaczął być używany przemyśle elektronicznym, pozostając praktycznie niezmienionym. Spopularyzował się w latach 60. XX w. wraz z publikacją arkuszy Letrasetu, zawierających fragmenty Lorem Ipsum, a ostatnio z zawierającym różne wersje Lorem Ipsum oprogramowaniem przeznaczonym do realizacji druków na komputerach osobistych, jak Aldus PageMaker', NULL, 1, 1455045897, 1455045897, 1, '', 'aaaaaaaa', 1),
(4, 'Mariusza pierwszy wpis edytowalny', '<p>L<span style="color:#A52A2A"><strong>orem ipsum dolor sit amet, consecte</strong></span>tur adipiscing elit. Proin nulla urna, tincidunt eu porttitor nec, aliquam at libero. Aenean nisl lorem, interdum ac euismod nec, consequat ac nisi. Etiam laoreet auctor sollicitudin. Maecenas vitae convallis turpis. In hac habitasse platea dictumst. Donec a rhoncus lectus, sed blandit nulla. Nullam nec tempor dolor. Fusce pretium a quam et efficitur. Ut eget purus feugiat, dictum lectus nec, tristique turpis.<u><span style="background-color:#EE82EE"> Aliquam ornare tortor non ipsum facilisis</span></u> efficitur. Ut dolor magna, pulvinar sit amet erat et, eleifend laoreet nisl. Duis eget ligula eget ex interdum tincidunt. Nunc nec neque tincidunt ex maximus venenatis. Vestibulum imperdiet enim non efficitur interdum. Nullam non justo ac arcu ultrices condimentum eu at ipsum. Suspendisse aliquet tristique libero non fermentum. Suspendisse quis nisl malesuada, posuere turpis id, laoreet metus. Pellentesque eget aliquet justo, vitae fringilla erat. In sed risus maximus, facilisis neque sodales, consequat libero. Etiam convallis porttitor risus vitae hendrerit. Duis ac magna quis diam malesuada tempus et eu sem. Suspendisse tincidunt tempus diam, non euismod lorem fringilla at. Suspendisse pellentesque tincidunt pretium. Sed a arcu facilisis, blandit urna quis, suscipit arcu. Aliquam placerat nibh ipsum, non malesuada turpis vulputate quis. Fusce aliquam nulla et eros vulputate, eu vulputate ante commodo. Phasellus scelerisque mauris in viverra pharetra. Nulla facilisi. Donec dignissim aliquet rutrum. Sed tortor orci, tincidunt et feugiat quis, aliquet at mauris. Fusce pellentesque dui congue mauris elementum, a eleifend enim tincidunt. Duis sed nunc aliquet, mattis enim in, tincidunt dui. Proin sed mi viverra, semper velit eget, porta mauris. Sed sed purus odio. Vivamus eu sollicitudin nulla, ut tristique elit. Mauris fermentum varius malesuada. Praesent laoreet quam libero, in semper dolor placerat quis. Donec vitae enim congue neque viverra vulputate. Mauris sit amet massa eleifend, rutrum lorem viverra, tincidunt nisi. Nulla sed ultrices massa, ut blandit tellus. Sed suscipit consectetur interdum. Phasellus sit amet orci gravida, lacinia massa id, efficitur libero. Morbi nisl lorem, tincidunt eu est porta, bibendum posuere tortor.</p>\r\n', 'Proin nulla urna, tincidunt eu porttitor nec, aliquam at libero. Aenean nisl lorem, interdum ac euismod nec, consequat ac nisi. Etiam la', 1, 1449299283, 1453842412, 1, 'test, MS, mariuszs', 'mariusza-pierwszy-wpis-edytowalny', 1),
(5, 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit', 'Lorem Ipsum jest tekstem stosowanym jako przykładowy wypełniacz w przemyśle poligraficznym. Został po raz pierwszy użyty w XV w. przez nieznanego drukarza do wypełnienia tekstem próbnej książki. Pięć wieków później zaczął być używany przemyśle elektronicznym, pozostając praktycznie niezmienionym. Spopularyzował się w latach 60. XX w. wraz z publikacją arkuszy Letrasetu, zawierających fragmenty Lorem Ipsum, a ostatnio z zawierającym różne wersje Lorem Ipsum oprogramowaniem przeznaczonym do realizacji druków na komputerach osobistych, jak Aldus PageMaker', NULL, 1, 1455045897, 1455045897, 1, '', 'aaaaaaaa', 1),
(6, 'Mariusza pierwszy wpis edytowalny', '<p>L<span style="color:#A52A2A"><strong>orem ipsum dolor sit amet, consecte</strong></span>tur adipiscing elit. Proin nulla urna, tincidunt eu porttitor nec, aliquam at libero. Aenean nisl lorem, interdum ac euismod nec, consequat ac nisi. Etiam laoreet auctor sollicitudin. Maecenas vitae convallis turpis. In hac habitasse platea dictumst. Donec a rhoncus lectus, sed blandit nulla. Nullam nec tempor dolor. Fusce pretium a quam et efficitur. Ut eget purus feugiat, dictum lectus nec, tristique turpis.<u><span style="background-color:#EE82EE"> Aliquam ornare tortor non ipsum facilisis</span></u> efficitur. Ut dolor magna, pulvinar sit amet erat et, eleifend laoreet nisl. Duis eget ligula eget ex interdum tincidunt. Nunc nec neque tincidunt ex maximus venenatis. Vestibulum imperdiet enim non efficitur interdum. Nullam non justo ac arcu ultrices condimentum eu at ipsum. Suspendisse aliquet tristique libero non fermentum. Suspendisse quis nisl malesuada, posuere turpis id, laoreet metus. Pellentesque eget aliquet justo, vitae fringilla erat. In sed risus maximus, facilisis neque sodales, consequat libero. Etiam convallis porttitor risus vitae hendrerit. Duis ac magna quis diam malesuada tempus et eu sem. Suspendisse tincidunt tempus diam, non euismod lorem fringilla at. Suspendisse pellentesque tincidunt pretium. Sed a arcu facilisis, blandit urna quis, suscipit arcu. Aliquam placerat nibh ipsum, non malesuada turpis vulputate quis. Fusce aliquam nulla et eros vulputate, eu vulputate ante commodo. Phasellus scelerisque mauris in viverra pharetra. Nulla facilisi. Donec dignissim aliquet rutrum. Sed tortor orci, tincidunt et feugiat quis, aliquet at mauris. Fusce pellentesque dui congue mauris elementum, a eleifend enim tincidunt. Duis sed nunc aliquet, mattis enim in, tincidunt dui. Proin sed mi viverra, semper velit eget, porta mauris. Sed sed purus odio. Vivamus eu sollicitudin nulla, ut tristique elit. Mauris fermentum varius malesuada. Praesent laoreet quam libero, in semper dolor placerat quis. Donec vitae enim congue neque viverra vulputate. Mauris sit amet massa eleifend, rutrum lorem viverra, tincidunt nisi. Nulla sed ultrices massa, ut blandit tellus. Sed suscipit consectetur interdum. Phasellus sit amet orci gravida, lacinia massa id, efficitur libero. Morbi nisl lorem, tincidunt eu est porta, bibendum posuere tortor.</p>\r\n', 'Proin nulla urna, tincidunt eu porttitor nec, aliquam at libero. Aenean nisl lorem, interdum ac euismod nec, consequat ac nisi. Etiam la', 1, 1449299283, 1453842412, 1, 'test, MS, mariuszs', 'mariusza-pierwszy-wpis-edytowalny', 1),
(7, 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit', 'Lorem Ipsum jest tekstem stosowanym jako przykładowy wypełniacz w przemyśle poligraficznym. Został po raz pierwszy użyty w XV w. przez nieznanego drukarza do wypełnienia tekstem próbnej książki. Pięć wieków później zaczął być używany przemyśle elektronicznym, pozostając praktycznie niezmienionym. Spopularyzował się w latach 60. XX w. wraz z publikacją arkuszy Letrasetu, zawierających fragmenty Lorem Ipsum, a ostatnio z zawierającym różne wersje Lorem Ipsum oprogramowaniem przeznaczonym do realizacji druków na komputerach osobistych, jak Aldus PageMaker', NULL, 1, 1455045897, 1455045897, 1, '', 'aaaaaaaa', 1),
(8, 'Mariusza pierwszy wpis edytowalny', '<p>L<span style="color:#A52A2A"><strong>orem ipsum dolor sit amet, consecte</strong></span>tur adipiscing elit. Proin nulla urna, tincidunt eu porttitor nec, aliquam at libero. Aenean nisl lorem, interdum ac euismod nec, consequat ac nisi. Etiam laoreet auctor sollicitudin. Maecenas vitae convallis turpis. In hac habitasse platea dictumst. Donec a rhoncus lectus, sed blandit nulla. Nullam nec tempor dolor. Fusce pretium a quam et efficitur. Ut eget purus feugiat, dictum lectus nec, tristique turpis.<u><span style="background-color:#EE82EE"> Aliquam ornare tortor non ipsum facilisis</span></u> efficitur. Ut dolor magna, pulvinar sit amet erat et, eleifend laoreet nisl. Duis eget ligula eget ex interdum tincidunt. Nunc nec neque tincidunt ex maximus venenatis. Vestibulum imperdiet enim non efficitur interdum. Nullam non justo ac arcu ultrices condimentum eu at ipsum. Suspendisse aliquet tristique libero non fermentum. Suspendisse quis nisl malesuada, posuere turpis id, laoreet metus. Pellentesque eget aliquet justo, vitae fringilla erat. In sed risus maximus, facilisis neque sodales, consequat libero. Etiam convallis porttitor risus vitae hendrerit. Duis ac magna quis diam malesuada tempus et eu sem. Suspendisse tincidunt tempus diam, non euismod lorem fringilla at. Suspendisse pellentesque tincidunt pretium. Sed a arcu facilisis, blandit urna quis, suscipit arcu. Aliquam placerat nibh ipsum, non malesuada turpis vulputate quis. Fusce aliquam nulla et eros vulputate, eu vulputate ante commodo. Phasellus scelerisque mauris in viverra pharetra. Nulla facilisi. Donec dignissim aliquet rutrum. Sed tortor orci, tincidunt et feugiat quis, aliquet at mauris. Fusce pellentesque dui congue mauris elementum, a eleifend enim tincidunt. Duis sed nunc aliquet, mattis enim in, tincidunt dui. Proin sed mi viverra, semper velit eget, porta mauris. Sed sed purus odio. Vivamus eu sollicitudin nulla, ut tristique elit. Mauris fermentum varius malesuada. Praesent laoreet quam libero, in semper dolor placerat quis. Donec vitae enim congue neque viverra vulputate. Mauris sit amet massa eleifend, rutrum lorem viverra, tincidunt nisi. Nulla sed ultrices massa, ut blandit tellus. Sed suscipit consectetur interdum. Phasellus sit amet orci gravida, lacinia massa id, efficitur libero. Morbi nisl lorem, tincidunt eu est porta, bibendum posuere tortor.</p>\r\n', 'Proin nulla urna, tincidunt eu porttitor nec, aliquam at libero. Aenean nisl lorem, interdum ac euismod nec, consequat ac nisi. Etiam la', 1, 1449299283, 1453842412, 1, 'test, MS, mariuszs', 'mariusza-pierwszy-wpis-edytowalny', 1),
(9, 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit', 'Lorem Ipsum jest tekstem stosowanym jako przykładowy wypełniacz w przemyśle poligraficznym. Został po raz pierwszy użyty w XV w. przez nieznanego drukarza do wypełnienia tekstem próbnej książki. Pięć wieków później zaczął być używany przemyśle elektronicznym, pozostając praktycznie niezmienionym. Spopularyzował się w latach 60. XX w. wraz z publikacją arkuszy Letrasetu, zawierających fragmenty Lorem Ipsum, a ostatnio z zawierającym różne wersje Lorem Ipsum oprogramowaniem przeznaczonym do realizacji druków na komputerach osobistych, jak Aldus PageMaker', NULL, 1, 1455045897, 1455045897, 1, '', 'aaaaaaaa', 1),
(10, 'Mariusza pierwszy wpis edytowalny', '<p>L<span style="color:#A52A2A"><strong>orem ipsum dolor sit amet, consecte</strong></span>tur adipiscing elit. Proin nulla urna, tincidunt eu porttitor nec, aliquam at libero. Aenean nisl lorem, interdum ac euismod nec, consequat ac nisi. Etiam laoreet auctor sollicitudin. Maecenas vitae convallis turpis. In hac habitasse platea dictumst. Donec a rhoncus lectus, sed blandit nulla. Nullam nec tempor dolor. Fusce pretium a quam et efficitur. Ut eget purus feugiat, dictum lectus nec, tristique turpis.<u><span style="background-color:#EE82EE"> Aliquam ornare tortor non ipsum facilisis</span></u> efficitur. Ut dolor magna, pulvinar sit amet erat et, eleifend laoreet nisl. Duis eget ligula eget ex interdum tincidunt. Nunc nec neque tincidunt ex maximus venenatis. Vestibulum imperdiet enim non efficitur interdum. Nullam non justo ac arcu ultrices condimentum eu at ipsum. Suspendisse aliquet tristique libero non fermentum. Suspendisse quis nisl malesuada, posuere turpis id, laoreet metus. Pellentesque eget aliquet justo, vitae fringilla erat. In sed risus maximus, facilisis neque sodales, consequat libero. Etiam convallis porttitor risus vitae hendrerit. Duis ac magna quis diam malesuada tempus et eu sem. Suspendisse tincidunt tempus diam, non euismod lorem fringilla at. Suspendisse pellentesque tincidunt pretium. Sed a arcu facilisis, blandit urna quis, suscipit arcu. Aliquam placerat nibh ipsum, non malesuada turpis vulputate quis. Fusce aliquam nulla et eros vulputate, eu vulputate ante commodo. Phasellus scelerisque mauris in viverra pharetra. Nulla facilisi. Donec dignissim aliquet rutrum. Sed tortor orci, tincidunt et feugiat quis, aliquet at mauris. Fusce pellentesque dui congue mauris elementum, a eleifend enim tincidunt. Duis sed nunc aliquet, mattis enim in, tincidunt dui. Proin sed mi viverra, semper velit eget, porta mauris. Sed sed purus odio. Vivamus eu sollicitudin nulla, ut tristique elit. Mauris fermentum varius malesuada. Praesent laoreet quam libero, in semper dolor placerat quis. Donec vitae enim congue neque viverra vulputate. Mauris sit amet massa eleifend, rutrum lorem viverra, tincidunt nisi. Nulla sed ultrices massa, ut blandit tellus. Sed suscipit consectetur interdum. Phasellus sit amet orci gravida, lacinia massa id, efficitur libero. Morbi nisl lorem, tincidunt eu est porta, bibendum posuere tortor.</p>\r\n', 'Proin nulla urna, tincidunt eu porttitor nec, aliquam at libero. Aenean nisl lorem, interdum ac euismod nec, consequat ac nisi. Etiam la', 1, 1449299283, 1453842412, 1, 'test, MS, mariuszs', 'mariusza-pierwszy-wpis-edytowalny', 1),
(11, 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit', 'Lorem Ipsum jest tekstem stosowanym jako przykładowy wypełniacz w przemyśle poligraficznym. Został po raz pierwszy użyty w XV w. przez nieznanego drukarza do wypełnienia tekstem próbnej książki. Pięć wieków później zaczął być używany przemyśle elektronicznym, pozostając praktycznie niezmienionym. Spopularyzował się w latach 60. XX w. wraz z publikacją arkuszy Letrasetu, zawierających fragmenty Lorem Ipsum, a ostatnio z zawierającym różne wersje Lorem Ipsum oprogramowaniem przeznaczonym do realizacji druków na komputerach osobistych, jak Aldus PageMaker', NULL, 1, 1455045897, 1455045897, 1, '', 'aaaaaaaa', 1),
(12, 'Mariusza pierwszy wpis edytowalny', '<p>L<span style="color:#A52A2A"><strong>orem ipsum dolor sit amet, consecte</strong></span>tur adipiscing elit. Proin nulla urna, tincidunt eu porttitor nec, aliquam at libero. Aenean nisl lorem, interdum ac euismod nec, consequat ac nisi. Etiam laoreet auctor sollicitudin. Maecenas vitae convallis turpis. In hac habitasse platea dictumst. Donec a rhoncus lectus, sed blandit nulla. Nullam nec tempor dolor. Fusce pretium a quam et efficitur. Ut eget purus feugiat, dictum lectus nec, tristique turpis.<u><span style="background-color:#EE82EE"> Aliquam ornare tortor non ipsum facilisis</span></u> efficitur. Ut dolor magna, pulvinar sit amet erat et, eleifend laoreet nisl. Duis eget ligula eget ex interdum tincidunt. Nunc nec neque tincidunt ex maximus venenatis. Vestibulum imperdiet enim non efficitur interdum. Nullam non justo ac arcu ultrices condimentum eu at ipsum. Suspendisse aliquet tristique libero non fermentum. Suspendisse quis nisl malesuada, posuere turpis id, laoreet metus. Pellentesque eget aliquet justo, vitae fringilla erat. In sed risus maximus, facilisis neque sodales, consequat libero. Etiam convallis porttitor risus vitae hendrerit. Duis ac magna quis diam malesuada tempus et eu sem. Suspendisse tincidunt tempus diam, non euismod lorem fringilla at. Suspendisse pellentesque tincidunt pretium. Sed a arcu facilisis, blandit urna quis, suscipit arcu. Aliquam placerat nibh ipsum, non malesuada turpis vulputate quis. Fusce aliquam nulla et eros vulputate, eu vulputate ante commodo. Phasellus scelerisque mauris in viverra pharetra. Nulla facilisi. Donec dignissim aliquet rutrum. Sed tortor orci, tincidunt et feugiat quis, aliquet at mauris. Fusce pellentesque dui congue mauris elementum, a eleifend enim tincidunt. Duis sed nunc aliquet, mattis enim in, tincidunt dui. Proin sed mi viverra, semper velit eget, porta mauris. Sed sed purus odio. Vivamus eu sollicitudin nulla, ut tristique elit. Mauris fermentum varius malesuada. Praesent laoreet quam libero, in semper dolor placerat quis. Donec vitae enim congue neque viverra vulputate. Mauris sit amet massa eleifend, rutrum lorem viverra, tincidunt nisi. Nulla sed ultrices massa, ut blandit tellus. Sed suscipit consectetur interdum. Phasellus sit amet orci gravida, lacinia massa id, efficitur libero. Morbi nisl lorem, tincidunt eu est porta, bibendum posuere tortor.</p>\r\n', 'Proin nulla urna, tincidunt eu porttitor nec, aliquam at libero. Aenean nisl lorem, interdum ac euismod nec, consequat ac nisi. Etiam la', 1, 1449299283, 1453842412, 1, 'test, MS, mariuszs', 'mariusza-pierwszy-wpis-edytowalny', 1),
(13, 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit', 'Lorem Ipsum jest tekstem stosowanym jako przykładowy wypełniacz w przemyśle poligraficznym. Został po raz pierwszy użyty w XV w. przez nieznanego drukarza do wypełnienia tekstem próbnej książki. Pięć wieków później zaczął być używany przemyśle elektronicznym, pozostając praktycznie niezmienionym. Spopularyzował się w latach 60. XX w. wraz z publikacją arkuszy Letrasetu, zawierających fragmenty Lorem Ipsum, a ostatnio z zawierającym różne wersje Lorem Ipsum oprogramowaniem przeznaczonym do realizacji druków na komputerach osobistych, jak Aldus PageMaker', NULL, 1, 1455045897, 1455045897, 1, '', 'aaaaaaaa', 1),
(14, 'Mariusza pierwszy wpis edytowalny', '<p>L<span style="color:#A52A2A"><strong>orem ipsum dolor sit amet, consecte</strong></span>tur adipiscing elit. Proin nulla urna, tincidunt eu porttitor nec, aliquam at libero. Aenean nisl lorem, interdum ac euismod nec, consequat ac nisi. Etiam laoreet auctor sollicitudin. Maecenas vitae convallis turpis. In hac habitasse platea dictumst. Donec a rhoncus lectus, sed blandit nulla. Nullam nec tempor dolor. Fusce pretium a quam et efficitur. Ut eget purus feugiat, dictum lectus nec, tristique turpis.<u><span style="background-color:#EE82EE"> Aliquam ornare tortor non ipsum facilisis</span></u> efficitur. Ut dolor magna, pulvinar sit amet erat et, eleifend laoreet nisl. Duis eget ligula eget ex interdum tincidunt. Nunc nec neque tincidunt ex maximus venenatis. Vestibulum imperdiet enim non efficitur interdum. Nullam non justo ac arcu ultrices condimentum eu at ipsum. Suspendisse aliquet tristique libero non fermentum. Suspendisse quis nisl malesuada, posuere turpis id, laoreet metus. Pellentesque eget aliquet justo, vitae fringilla erat. In sed risus maximus, facilisis neque sodales, consequat libero. Etiam convallis porttitor risus vitae hendrerit. Duis ac magna quis diam malesuada tempus et eu sem. Suspendisse tincidunt tempus diam, non euismod lorem fringilla at. Suspendisse pellentesque tincidunt pretium. Sed a arcu facilisis, blandit urna quis, suscipit arcu. Aliquam placerat nibh ipsum, non malesuada turpis vulputate quis. Fusce aliquam nulla et eros vulputate, eu vulputate ante commodo. Phasellus scelerisque mauris in viverra pharetra. Nulla facilisi. Donec dignissim aliquet rutrum. Sed tortor orci, tincidunt et feugiat quis, aliquet at mauris. Fusce pellentesque dui congue mauris elementum, a eleifend enim tincidunt. Duis sed nunc aliquet, mattis enim in, tincidunt dui. Proin sed mi viverra, semper velit eget, porta mauris. Sed sed purus odio. Vivamus eu sollicitudin nulla, ut tristique elit. Mauris fermentum varius malesuada. Praesent laoreet quam libero, in semper dolor placerat quis. Donec vitae enim congue neque viverra vulputate. Mauris sit amet massa eleifend, rutrum lorem viverra, tincidunt nisi. Nulla sed ultrices massa, ut blandit tellus. Sed suscipit consectetur interdum. Phasellus sit amet orci gravida, lacinia massa id, efficitur libero. Morbi nisl lorem, tincidunt eu est porta, bibendum posuere tortor.</p>\r\n', 'Proin nulla urna, tincidunt eu porttitor nec, aliquam at libero. Aenean nisl lorem, interdum ac euismod nec, consequat ac nisi. Etiam la', 1, 1449299283, 1453842412, 1, 'test, MS, mariuszs', 'mariusza-pierwszy-wpis-edytowalny', 1),
(15, 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit', 'Lorem Ipsum jest tekstem stosowanym jako przykładowy wypełniacz w przemyśle poligraficznym. Został po raz pierwszy użyty w XV w. przez nieznanego drukarza do wypełnienia tekstem próbnej książki. Pięć wieków później zaczął być używany przemyśle elektronicznym, pozostając praktycznie niezmienionym. Spopularyzował się w latach 60. XX w. wraz z publikacją arkuszy Letrasetu, zawierających fragmenty Lorem Ipsum, a ostatnio z zawierającym różne wersje Lorem Ipsum oprogramowaniem przeznaczonym do realizacji druków na komputerach osobistych, jak Aldus PageMaker', NULL, 1, 1455045897, 1455045897, 1, '', 'aaaaaaaa', 1),
(16, 'Mariusza pierwszy wpis edytowalny', '<p>L<span style="color:#A52A2A"><strong>orem ipsum dolor sit amet, consecte</strong></span>tur adipiscing elit. Proin nulla urna, tincidunt eu porttitor nec, aliquam at libero. Aenean nisl lorem, interdum ac euismod nec, consequat ac nisi. Etiam laoreet auctor sollicitudin. Maecenas vitae convallis turpis. In hac habitasse platea dictumst. Donec a rhoncus lectus, sed blandit nulla. Nullam nec tempor dolor. Fusce pretium a quam et efficitur. Ut eget purus feugiat, dictum lectus nec, tristique turpis.<u><span style="background-color:#EE82EE"> Aliquam ornare tortor non ipsum facilisis</span></u> efficitur. Ut dolor magna, pulvinar sit amet erat et, eleifend laoreet nisl. Duis eget ligula eget ex interdum tincidunt. Nunc nec neque tincidunt ex maximus venenatis. Vestibulum imperdiet enim non efficitur interdum. Nullam non justo ac arcu ultrices condimentum eu at ipsum. Suspendisse aliquet tristique libero non fermentum. Suspendisse quis nisl malesuada, posuere turpis id, laoreet metus. Pellentesque eget aliquet justo, vitae fringilla erat. In sed risus maximus, facilisis neque sodales, consequat libero. Etiam convallis porttitor risus vitae hendrerit. Duis ac magna quis diam malesuada tempus et eu sem. Suspendisse tincidunt tempus diam, non euismod lorem fringilla at. Suspendisse pellentesque tincidunt pretium. Sed a arcu facilisis, blandit urna quis, suscipit arcu. Aliquam placerat nibh ipsum, non malesuada turpis vulputate quis. Fusce aliquam nulla et eros vulputate, eu vulputate ante commodo. Phasellus scelerisque mauris in viverra pharetra. Nulla facilisi. Donec dignissim aliquet rutrum. Sed tortor orci, tincidunt et feugiat quis, aliquet at mauris. Fusce pellentesque dui congue mauris elementum, a eleifend enim tincidunt. Duis sed nunc aliquet, mattis enim in, tincidunt dui. Proin sed mi viverra, semper velit eget, porta mauris. Sed sed purus odio. Vivamus eu sollicitudin nulla, ut tristique elit. Mauris fermentum varius malesuada. Praesent laoreet quam libero, in semper dolor placerat quis. Donec vitae enim congue neque viverra vulputate. Mauris sit amet massa eleifend, rutrum lorem viverra, tincidunt nisi. Nulla sed ultrices massa, ut blandit tellus. Sed suscipit consectetur interdum. Phasellus sit amet orci gravida, lacinia massa id, efficitur libero. Morbi nisl lorem, tincidunt eu est porta, bibendum posuere tortor.</p>\r\n', 'Proin nulla urna, tincidunt eu porttitor nec, aliquam at libero. Aenean nisl lorem, interdum ac euismod nec, consequat ac nisi. Etiam la', 1, 1449299283, 1453842412, 1, 'test, MS, mariuszs', 'mariusza-pierwszy-wpis-edytowalny', 1),
(17, 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit', 'Lorem Ipsum jest tekstem stosowanym jako przykładowy wypełniacz w przemyśle poligraficznym. Został po raz pierwszy użyty w XV w. przez nieznanego drukarza do wypełnienia tekstem próbnej książki. Pięć wieków później zaczął być używany przemyśle elektronicznym, pozostając praktycznie niezmienionym. Spopularyzował się w latach 60. XX w. wraz z publikacją arkuszy Letrasetu, zawierających fragmenty Lorem Ipsum, a ostatnio z zawierającym różne wersje Lorem Ipsum oprogramowaniem przeznaczonym do realizacji druków na komputerach osobistych, jak Aldus PageMaker', NULL, 1, 1455045897, 1455045897, 1, '', 'aaaaaaaa', 1),
(18, 'Mariusza pierwszy wpis edytowalny', '<p>L<span style="color:#A52A2A"><strong>orem ipsum dolor sit amet, consecte</strong></span>tur adipiscing elit. Proin nulla urna, tincidunt eu porttitor nec, aliquam at libero. Aenean nisl lorem, interdum ac euismod nec, consequat ac nisi. Etiam laoreet auctor sollicitudin. Maecenas vitae convallis turpis. In hac habitasse platea dictumst. Donec a rhoncus lectus, sed blandit nulla. Nullam nec tempor dolor. Fusce pretium a quam et efficitur. Ut eget purus feugiat, dictum lectus nec, tristique turpis.<u><span style="background-color:#EE82EE"> Aliquam ornare tortor non ipsum facilisis</span></u> efficitur. Ut dolor magna, pulvinar sit amet erat et, eleifend laoreet nisl. Duis eget ligula eget ex interdum tincidunt. Nunc nec neque tincidunt ex maximus venenatis. Vestibulum imperdiet enim non efficitur interdum. Nullam non justo ac arcu ultrices condimentum eu at ipsum. Suspendisse aliquet tristique libero non fermentum. Suspendisse quis nisl malesuada, posuere turpis id, laoreet metus. Pellentesque eget aliquet justo, vitae fringilla erat. In sed risus maximus, facilisis neque sodales, consequat libero. Etiam convallis porttitor risus vitae hendrerit. Duis ac magna quis diam malesuada tempus et eu sem. Suspendisse tincidunt tempus diam, non euismod lorem fringilla at. Suspendisse pellentesque tincidunt pretium. Sed a arcu facilisis, blandit urna quis, suscipit arcu. Aliquam placerat nibh ipsum, non malesuada turpis vulputate quis. Fusce aliquam nulla et eros vulputate, eu vulputate ante commodo. Phasellus scelerisque mauris in viverra pharetra. Nulla facilisi. Donec dignissim aliquet rutrum. Sed tortor orci, tincidunt et feugiat quis, aliquet at mauris. Fusce pellentesque dui congue mauris elementum, a eleifend enim tincidunt. Duis sed nunc aliquet, mattis enim in, tincidunt dui. Proin sed mi viverra, semper velit eget, porta mauris. Sed sed purus odio. Vivamus eu sollicitudin nulla, ut tristique elit. Mauris fermentum varius malesuada. Praesent laoreet quam libero, in semper dolor placerat quis. Donec vitae enim congue neque viverra vulputate. Mauris sit amet massa eleifend, rutrum lorem viverra, tincidunt nisi. Nulla sed ultrices massa, ut blandit tellus. Sed suscipit consectetur interdum. Phasellus sit amet orci gravida, lacinia massa id, efficitur libero. Morbi nisl lorem, tincidunt eu est porta, bibendum posuere tortor.</p>\r\n', 'Proin nulla urna, tincidunt eu porttitor nec, aliquam at libero. Aenean nisl lorem, interdum ac euismod nec, consequat ac nisi. Etiam la', 1, 1449299283, 1453842412, 1, 'test, MS, mariuszs', 'mariusza-pierwszy-wpis-edytowalny', 1),
(19, 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit', 'Lorem Ipsum jest tekstem stosowanym jako przykładowy wypełniacz w przemyśle poligraficznym. Został po raz pierwszy użyty w XV w. przez nieznanego drukarza do wypełnienia tekstem próbnej książki. Pięć wieków później zaczął być używany przemyśle elektronicznym, pozostając praktycznie niezmienionym. Spopularyzował się w latach 60. XX w. wraz z publikacją arkuszy Letrasetu, zawierających fragmenty Lorem Ipsum, a ostatnio z zawierającym różne wersje Lorem Ipsum oprogramowaniem przeznaczonym do realizacji druków na komputerach osobistych, jak Aldus PageMaker', NULL, 1, 1455045897, 1455045897, 1, '', 'aaaaaaaa', 1),
(20, 'Mariusza pierwszy wpis edytowalny', '<p>L<span style="color:#A52A2A"><strong>orem ipsum dolor sit amet, consecte</strong></span>tur adipiscing elit. Proin nulla urna, tincidunt eu porttitor nec, aliquam at libero. Aenean nisl lorem, interdum ac euismod nec, consequat ac nisi. Etiam laoreet auctor sollicitudin. Maecenas vitae convallis turpis. In hac habitasse platea dictumst. Donec a rhoncus lectus, sed blandit nulla. Nullam nec tempor dolor. Fusce pretium a quam et efficitur. Ut eget purus feugiat, dictum lectus nec, tristique turpis.<u><span style="background-color:#EE82EE"> Aliquam ornare tortor non ipsum facilisis</span></u> efficitur. Ut dolor magna, pulvinar sit amet erat et, eleifend laoreet nisl. Duis eget ligula eget ex interdum tincidunt. Nunc nec neque tincidunt ex maximus venenatis. Vestibulum imperdiet enim non efficitur interdum. Nullam non justo ac arcu ultrices condimentum eu at ipsum. Suspendisse aliquet tristique libero non fermentum. Suspendisse quis nisl malesuada, posuere turpis id, laoreet metus. Pellentesque eget aliquet justo, vitae fringilla erat. In sed risus maximus, facilisis neque sodales, consequat libero. Etiam convallis porttitor risus vitae hendrerit. Duis ac magna quis diam malesuada tempus et eu sem. Suspendisse tincidunt tempus diam, non euismod lorem fringilla at. Suspendisse pellentesque tincidunt pretium. Sed a arcu facilisis, blandit urna quis, suscipit arcu. Aliquam placerat nibh ipsum, non malesuada turpis vulputate quis. Fusce aliquam nulla et eros vulputate, eu vulputate ante commodo. Phasellus scelerisque mauris in viverra pharetra. Nulla facilisi. Donec dignissim aliquet rutrum. Sed tortor orci, tincidunt et feugiat quis, aliquet at mauris. Fusce pellentesque dui congue mauris elementum, a eleifend enim tincidunt. Duis sed nunc aliquet, mattis enim in, tincidunt dui. Proin sed mi viverra, semper velit eget, porta mauris. Sed sed purus odio. Vivamus eu sollicitudin nulla, ut tristique elit. Mauris fermentum varius malesuada. Praesent laoreet quam libero, in semper dolor placerat quis. Donec vitae enim congue neque viverra vulputate. Mauris sit amet massa eleifend, rutrum lorem viverra, tincidunt nisi. Nulla sed ultrices massa, ut blandit tellus. Sed suscipit consectetur interdum. Phasellus sit amet orci gravida, lacinia massa id, efficitur libero. Morbi nisl lorem, tincidunt eu est porta, bibendum posuere tortor.</p>\r\n', 'Proin nulla urna, tincidunt eu porttitor nec, aliquam at libero. Aenean nisl lorem, interdum ac euismod nec, consequat ac nisi. Etiam la', 1, 1449299283, 1453842412, 1, 'test, MS, mariuszs', 'mariusza-pierwszy-wpis-edytowalny', 1),
(21, 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit', 'Lorem Ipsum jest tekstem stosowanym jako przykładowy wypełniacz w przemyśle poligraficznym. Został po raz pierwszy użyty w XV w. przez nieznanego drukarza do wypełnienia tekstem próbnej książki. Pięć wieków później zaczął być używany przemyśle elektronicznym, pozostając praktycznie niezmienionym. Spopularyzował się w latach 60. XX w. wraz z publikacją arkuszy Letrasetu, zawierających fragmenty Lorem Ipsum, a ostatnio z zawierającym różne wersje Lorem Ipsum oprogramowaniem przeznaczonym do realizacji druków na komputerach osobistych, jak Aldus PageMaker', NULL, 1, 1455045897, 1455045897, 1, '', 'aaaaaaaa', 1),
(22, 'Mariusza pierwszy wpis edytowalny', '<p>L<span style="color:#A52A2A"><strong>orem ipsum dolor sit amet, consecte</strong></span>tur adipiscing elit. Proin nulla urna, tincidunt eu porttitor nec, aliquam at libero. Aenean nisl lorem, interdum ac euismod nec, consequat ac nisi. Etiam laoreet auctor sollicitudin. Maecenas vitae convallis turpis. In hac habitasse platea dictumst. Donec a rhoncus lectus, sed blandit nulla. Nullam nec tempor dolor. Fusce pretium a quam et efficitur. Ut eget purus feugiat, dictum lectus nec, tristique turpis.<u><span style="background-color:#EE82EE"> Aliquam ornare tortor non ipsum facilisis</span></u> efficitur. Ut dolor magna, pulvinar sit amet erat et, eleifend laoreet nisl. Duis eget ligula eget ex interdum tincidunt. Nunc nec neque tincidunt ex maximus venenatis. Vestibulum imperdiet enim non efficitur interdum. Nullam non justo ac arcu ultrices condimentum eu at ipsum. Suspendisse aliquet tristique libero non fermentum. Suspendisse quis nisl malesuada, posuere turpis id, laoreet metus. Pellentesque eget aliquet justo, vitae fringilla erat. In sed risus maximus, facilisis neque sodales, consequat libero. Etiam convallis porttitor risus vitae hendrerit. Duis ac magna quis diam malesuada tempus et eu sem. Suspendisse tincidunt tempus diam, non euismod lorem fringilla at. Suspendisse pellentesque tincidunt pretium. Sed a arcu facilisis, blandit urna quis, suscipit arcu. Aliquam placerat nibh ipsum, non malesuada turpis vulputate quis. Fusce aliquam nulla et eros vulputate, eu vulputate ante commodo. Phasellus scelerisque mauris in viverra pharetra. Nulla facilisi. Donec dignissim aliquet rutrum. Sed tortor orci, tincidunt et feugiat quis, aliquet at mauris. Fusce pellentesque dui congue mauris elementum, a eleifend enim tincidunt. Duis sed nunc aliquet, mattis enim in, tincidunt dui. Proin sed mi viverra, semper velit eget, porta mauris. Sed sed purus odio. Vivamus eu sollicitudin nulla, ut tristique elit. Mauris fermentum varius malesuada. Praesent laoreet quam libero, in semper dolor placerat quis. Donec vitae enim congue neque viverra vulputate. Mauris sit amet massa eleifend, rutrum lorem viverra, tincidunt nisi. Nulla sed ultrices massa, ut blandit tellus. Sed suscipit consectetur interdum. Phasellus sit amet orci gravida, lacinia massa id, efficitur libero. Morbi nisl lorem, tincidunt eu est porta, bibendum posuere tortor.</p>\r\n', 'Proin nulla urna, tincidunt eu porttitor nec, aliquam at libero. Aenean nisl lorem, interdum ac euismod nec, consequat ac nisi. Etiam la', 1, 1449299283, 1453842412, 1, 'test, MS, mariuszs', 'mariusza-pierwszy-wpis-edytowalny', 1),
(23, 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit', 'Lorem Ipsum jest tekstem stosowanym jako przykładowy wypełniacz w przemyśle poligraficznym. Został po raz pierwszy użyty w XV w. przez nieznanego drukarza do wypełnienia tekstem próbnej książki. Pięć wieków później zaczął być używany przemyśle elektronicznym, pozostając praktycznie niezmienionym. Spopularyzował się w latach 60. XX w. wraz z publikacją arkuszy Letrasetu, zawierających fragmenty Lorem Ipsum, a ostatnio z zawierającym różne wersje Lorem Ipsum oprogramowaniem przeznaczonym do realizacji druków na komputerach osobistych, jak Aldus PageMaker', NULL, 1, 1455045897, 1455045897, 1, '', 'aaaaaaaa', 1),
(24, 'Mariusza pierwszy wpis edytowalny', '<p>L<span style="color:#A52A2A"><strong>orem ipsum dolor sit amet, consecte</strong></span>tur adipiscing elit. Proin nulla urna, tincidunt eu porttitor nec, aliquam at libero. Aenean nisl lorem, interdum ac euismod nec, consequat ac nisi. Etiam laoreet auctor sollicitudin. Maecenas vitae convallis turpis. In hac habitasse platea dictumst. Donec a rhoncus lectus, sed blandit nulla. Nullam nec tempor dolor. Fusce pretium a quam et efficitur. Ut eget purus feugiat, dictum lectus nec, tristique turpis.<u><span style="background-color:#EE82EE"> Aliquam ornare tortor non ipsum facilisis</span></u> efficitur. Ut dolor magna, pulvinar sit amet erat et, eleifend laoreet nisl. Duis eget ligula eget ex interdum tincidunt. Nunc nec neque tincidunt ex maximus venenatis. Vestibulum imperdiet enim non efficitur interdum. Nullam non justo ac arcu ultrices condimentum eu at ipsum. Suspendisse aliquet tristique libero non fermentum. Suspendisse quis nisl malesuada, posuere turpis id, laoreet metus. Pellentesque eget aliquet justo, vitae fringilla erat. In sed risus maximus, facilisis neque sodales, consequat libero. Etiam convallis porttitor risus vitae hendrerit. Duis ac magna quis diam malesuada tempus et eu sem. Suspendisse tincidunt tempus diam, non euismod lorem fringilla at. Suspendisse pellentesque tincidunt pretium. Sed a arcu facilisis, blandit urna quis, suscipit arcu. Aliquam placerat nibh ipsum, non malesuada turpis vulputate quis. Fusce aliquam nulla et eros vulputate, eu vulputate ante commodo. Phasellus scelerisque mauris in viverra pharetra. Nulla facilisi. Donec dignissim aliquet rutrum. Sed tortor orci, tincidunt et feugiat quis, aliquet at mauris. Fusce pellentesque dui congue mauris elementum, a eleifend enim tincidunt. Duis sed nunc aliquet, mattis enim in, tincidunt dui. Proin sed mi viverra, semper velit eget, porta mauris. Sed sed purus odio. Vivamus eu sollicitudin nulla, ut tristique elit. Mauris fermentum varius malesuada. Praesent laoreet quam libero, in semper dolor placerat quis. Donec vitae enim congue neque viverra vulputate. Mauris sit amet massa eleifend, rutrum lorem viverra, tincidunt nisi. Nulla sed ultrices massa, ut blandit tellus. Sed suscipit consectetur interdum. Phasellus sit amet orci gravida, lacinia massa id, efficitur libero. Morbi nisl lorem, tincidunt eu est porta, bibendum posuere tortor.</p>\r\n', 'Proin nulla urna, tincidunt eu porttitor nec, aliquam at libero. Aenean nisl lorem, interdum ac euismod nec, consequat ac nisi. Etiam la', 1, 1449299283, 1453842412, 1, 'test, MS, mariuszs', 'mariusza-pierwszy-wpis-edytowalny', 1),
(25, 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit', 'Lorem Ipsum jest tekstem stosowanym jako przykładowy wypełniacz w przemyśle poligraficznym. Został po raz pierwszy użyty w XV w. przez nieznanego drukarza do wypełnienia tekstem próbnej książki. Pięć wieków później zaczął być używany przemyśle elektronicznym, pozostając praktycznie niezmienionym. Spopularyzował się w latach 60. XX w. wraz z publikacją arkuszy Letrasetu, zawierających fragmenty Lorem Ipsum, a ostatnio z zawierającym różne wersje Lorem Ipsum oprogramowaniem przeznaczonym do realizacji druków na komputerach osobistych, jak Aldus PageMaker', NULL, 1, 1455045897, 1455045897, 1, '', 'aaaaaaaa', 1),
(26, 'Mariusza pierwszy wpis edytowalny', '<p>L<span style="color:#A52A2A"><strong>orem ipsum dolor sit amet, consecte</strong></span>tur adipiscing elit. Proin nulla urna, tincidunt eu porttitor nec, aliquam at libero. Aenean nisl lorem, interdum ac euismod nec, consequat ac nisi. Etiam laoreet auctor sollicitudin. Maecenas vitae convallis turpis. In hac habitasse platea dictumst. Donec a rhoncus lectus, sed blandit nulla. Nullam nec tempor dolor. Fusce pretium a quam et efficitur. Ut eget purus feugiat, dictum lectus nec, tristique turpis.<u><span style="background-color:#EE82EE"> Aliquam ornare tortor non ipsum facilisis</span></u> efficitur. Ut dolor magna, pulvinar sit amet erat et, eleifend laoreet nisl. Duis eget ligula eget ex interdum tincidunt. Nunc nec neque tincidunt ex maximus venenatis. Vestibulum imperdiet enim non efficitur interdum. Nullam non justo ac arcu ultrices condimentum eu at ipsum. Suspendisse aliquet tristique libero non fermentum. Suspendisse quis nisl malesuada, posuere turpis id, laoreet metus. Pellentesque eget aliquet justo, vitae fringilla erat. In sed risus maximus, facilisis neque sodales, consequat libero. Etiam convallis porttitor risus vitae hendrerit. Duis ac magna quis diam malesuada tempus et eu sem. Suspendisse tincidunt tempus diam, non euismod lorem fringilla at. Suspendisse pellentesque tincidunt pretium. Sed a arcu facilisis, blandit urna quis, suscipit arcu. Aliquam placerat nibh ipsum, non malesuada turpis vulputate quis. Fusce aliquam nulla et eros vulputate, eu vulputate ante commodo. Phasellus scelerisque mauris in viverra pharetra. Nulla facilisi. Donec dignissim aliquet rutrum. Sed tortor orci, tincidunt et feugiat quis, aliquet at mauris. Fusce pellentesque dui congue mauris elementum, a eleifend enim tincidunt. Duis sed nunc aliquet, mattis enim in, tincidunt dui. Proin sed mi viverra, semper velit eget, porta mauris. Sed sed purus odio. Vivamus eu sollicitudin nulla, ut tristique elit. Mauris fermentum varius malesuada. Praesent laoreet quam libero, in semper dolor placerat quis. Donec vitae enim congue neque viverra vulputate. Mauris sit amet massa eleifend, rutrum lorem viverra, tincidunt nisi. Nulla sed ultrices massa, ut blandit tellus. Sed suscipit consectetur interdum. Phasellus sit amet orci gravida, lacinia massa id, efficitur libero. Morbi nisl lorem, tincidunt eu est porta, bibendum posuere tortor.</p>\r\n', 'Proin nulla urna, tincidunt eu porttitor nec, aliquam at libero. Aenean nisl lorem, interdum ac euismod nec, consequat ac nisi. Etiam la', 1, 1449299283, 1453842412, 1, 'test, MS, mariuszs', 'mariusza-pierwszy-wpis-edytowalny', 1),
(27, 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit', 'Lorem Ipsum jest tekstem stosowanym jako przykładowy wypełniacz w przemyśle poligraficznym. Został po raz pierwszy użyty w XV w. przez nieznanego drukarza do wypełnienia tekstem próbnej książki. Pięć wieków później zaczął być używany przemyśle elektronicznym, pozostając praktycznie niezmienionym. Spopularyzował się w latach 60. XX w. wraz z publikacją arkuszy Letrasetu, zawierających fragmenty Lorem Ipsum, a ostatnio z zawierającym różne wersje Lorem Ipsum oprogramowaniem przeznaczonym do realizacji druków na komputerach osobistych, jak Aldus PageMaker', NULL, 1, 1455045897, 1455045897, 1, '', 'aaaaaaaa', 1),
(28, 'Mariusza pierwszy wpis edytowalny', '<p>L<span style="color:#A52A2A"><strong>orem ipsum dolor sit amet, consecte</strong></span>tur adipiscing elit. Proin nulla urna, tincidunt eu porttitor nec, aliquam at libero. Aenean nisl lorem, interdum ac euismod nec, consequat ac nisi. Etiam laoreet auctor sollicitudin. Maecenas vitae convallis turpis. In hac habitasse platea dictumst. Donec a rhoncus lectus, sed blandit nulla. Nullam nec tempor dolor. Fusce pretium a quam et efficitur. Ut eget purus feugiat, dictum lectus nec, tristique turpis.<u><span style="background-color:#EE82EE"> Aliquam ornare tortor non ipsum facilisis</span></u> efficitur. Ut dolor magna, pulvinar sit amet erat et, eleifend laoreet nisl. Duis eget ligula eget ex interdum tincidunt. Nunc nec neque tincidunt ex maximus venenatis. Vestibulum imperdiet enim non efficitur interdum. Nullam non justo ac arcu ultrices condimentum eu at ipsum. Suspendisse aliquet tristique libero non fermentum. Suspendisse quis nisl malesuada, posuere turpis id, laoreet metus. Pellentesque eget aliquet justo, vitae fringilla erat. In sed risus maximus, facilisis neque sodales, consequat libero. Etiam convallis porttitor risus vitae hendrerit. Duis ac magna quis diam malesuada tempus et eu sem. Suspendisse tincidunt tempus diam, non euismod lorem fringilla at. Suspendisse pellentesque tincidunt pretium. Sed a arcu facilisis, blandit urna quis, suscipit arcu. Aliquam placerat nibh ipsum, non malesuada turpis vulputate quis. Fusce aliquam nulla et eros vulputate, eu vulputate ante commodo. Phasellus scelerisque mauris in viverra pharetra. Nulla facilisi. Donec dignissim aliquet rutrum. Sed tortor orci, tincidunt et feugiat quis, aliquet at mauris. Fusce pellentesque dui congue mauris elementum, a eleifend enim tincidunt. Duis sed nunc aliquet, mattis enim in, tincidunt dui. Proin sed mi viverra, semper velit eget, porta mauris. Sed sed purus odio. Vivamus eu sollicitudin nulla, ut tristique elit. Mauris fermentum varius malesuada. Praesent laoreet quam libero, in semper dolor placerat quis. Donec vitae enim congue neque viverra vulputate. Mauris sit amet massa eleifend, rutrum lorem viverra, tincidunt nisi. Nulla sed ultrices massa, ut blandit tellus. Sed suscipit consectetur interdum. Phasellus sit amet orci gravida, lacinia massa id, efficitur libero. Morbi nisl lorem, tincidunt eu est porta, bibendum posuere tortor.</p>\r\n', 'Proin nulla urna, tincidunt eu porttitor nec, aliquam at libero. Aenean nisl lorem, interdum ac euismod nec, consequat ac nisi. Etiam la', 1, 1449299283, 1453842412, 1, 'test, MS, mariuszs', 'mariusza-pierwszy-wpis-edytowalny', 1),
(29, 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit', 'Lorem Ipsum jest tekstem stosowanym jako przykładowy wypełniacz w przemyśle poligraficznym. Został po raz pierwszy użyty w XV w. przez nieznanego drukarza do wypełnienia tekstem próbnej książki. Pięć wieków później zaczął być używany przemyśle elektronicznym, pozostając praktycznie niezmienionym. Spopularyzował się w latach 60. XX w. wraz z publikacją arkuszy Letrasetu, zawierających fragmenty Lorem Ipsum, a ostatnio z zawierającym różne wersje Lorem Ipsum oprogramowaniem przeznaczonym do realizacji druków na komputerach osobistych, jak Aldus PageMaker', NULL, 1, 1455045897, 1455045897, 1, '', 'aaaaaaaa', 1),
(30, 'Mariusza pierwszy wpis edytowalny', '<p>L<span style="color:#A52A2A"><strong>orem ipsum dolor sit amet, consecte</strong></span>tur adipiscing elit. Proin nulla urna, tincidunt eu porttitor nec, aliquam at libero. Aenean nisl lorem, interdum ac euismod nec, consequat ac nisi. Etiam laoreet auctor sollicitudin. Maecenas vitae convallis turpis. In hac habitasse platea dictumst. Donec a rhoncus lectus, sed blandit nulla. Nullam nec tempor dolor. Fusce pretium a quam et efficitur. Ut eget purus feugiat, dictum lectus nec, tristique turpis.<u><span style="background-color:#EE82EE"> Aliquam ornare tortor non ipsum facilisis</span></u> efficitur. Ut dolor magna, pulvinar sit amet erat et, eleifend laoreet nisl. Duis eget ligula eget ex interdum tincidunt. Nunc nec neque tincidunt ex maximus venenatis. Vestibulum imperdiet enim non efficitur interdum. Nullam non justo ac arcu ultrices condimentum eu at ipsum. Suspendisse aliquet tristique libero non fermentum. Suspendisse quis nisl malesuada, posuere turpis id, laoreet metus. Pellentesque eget aliquet justo, vitae fringilla erat. In sed risus maximus, facilisis neque sodales, consequat libero. Etiam convallis porttitor risus vitae hendrerit. Duis ac magna quis diam malesuada tempus et eu sem. Suspendisse tincidunt tempus diam, non euismod lorem fringilla at. Suspendisse pellentesque tincidunt pretium. Sed a arcu facilisis, blandit urna quis, suscipit arcu. Aliquam placerat nibh ipsum, non malesuada turpis vulputate quis. Fusce aliquam nulla et eros vulputate, eu vulputate ante commodo. Phasellus scelerisque mauris in viverra pharetra. Nulla facilisi. Donec dignissim aliquet rutrum. Sed tortor orci, tincidunt et feugiat quis, aliquet at mauris. Fusce pellentesque dui congue mauris elementum, a eleifend enim tincidunt. Duis sed nunc aliquet, mattis enim in, tincidunt dui. Proin sed mi viverra, semper velit eget, porta mauris. Sed sed purus odio. Vivamus eu sollicitudin nulla, ut tristique elit. Mauris fermentum varius malesuada. Praesent laoreet quam libero, in semper dolor placerat quis. Donec vitae enim congue neque viverra vulputate. Mauris sit amet massa eleifend, rutrum lorem viverra, tincidunt nisi. Nulla sed ultrices massa, ut blandit tellus. Sed suscipit consectetur interdum. Phasellus sit amet orci gravida, lacinia massa id, efficitur libero. Morbi nisl lorem, tincidunt eu est porta, bibendum posuere tortor.</p>\r\n', 'Proin nulla urna, tincidunt eu porttitor nec, aliquam at libero. Aenean nisl lorem, interdum ac euismod nec, consequat ac nisi. Etiam la', 1, 1449299283, 1453842412, 1, 'test, MS, mariuszs', 'mariusza-pierwszy-wpis-edytowalny', 1);
INSERT INTO `post` (`id`, `title`, `content`, `short_content`, `user_id`, `data_creation`, `last_modification`, `is_active`, `tags`, `nice_link`, `category_id`) VALUES
(31, 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit', 'Lorem Ipsum jest tekstem stosowanym jako przykładowy wypełniacz w przemyśle poligraficznym. Został po raz pierwszy użyty w XV w. przez nieznanego drukarza do wypełnienia tekstem próbnej książki. Pięć wieków później zaczął być używany przemyśle elektronicznym, pozostając praktycznie niezmienionym. Spopularyzował się w latach 60. XX w. wraz z publikacją arkuszy Letrasetu, zawierających fragmenty Lorem Ipsum, a ostatnio z zawierającym różne wersje Lorem Ipsum oprogramowaniem przeznaczonym do realizacji druków na komputerach osobistych, jak Aldus PageMaker', NULL, 1, 1455045897, 1455045897, 1, '', 'aaaaaaaa', 1);

-- --------------------------------------------------------

--
-- Struktura tabeli dla tabeli `roles`
--

CREATE TABLE `roles` (
  `id` int(11) NOT NULL,
  `name` varchar(100) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin2;

--
-- Zrzut danych tabeli `roles`
--

INSERT INTO `roles` (`id`, `name`) VALUES
(1, 'Admin'),
(2, 'Edytor'),
(3, 'SuperAdmin');

-- --------------------------------------------------------

--
-- Struktura tabeli dla tabeli `user`
--

CREATE TABLE `user` (
  `id` int(11) NOT NULL,
  `username` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `firstname` varchar(24) COLLATE utf8_unicode_ci DEFAULT NULL,
  `lastname` varchar(24) COLLATE utf8_unicode_ci DEFAULT NULL,
  `auth_key` varchar(32) COLLATE utf8_unicode_ci NOT NULL,
  `password` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `password_reset_token` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `email` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `status` smallint(6) DEFAULT '10',
  `created_at` int(11) NOT NULL,
  `updated_at` int(11) NOT NULL,
  `role_id` int(11) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

--
-- Zrzut danych tabeli `user`
--

INSERT INTO `user` (`id`, `username`, `firstname`, `lastname`, `auth_key`, `password`, `password_reset_token`, `email`, `status`, `created_at`, `updated_at`, `role_id`) VALUES
(1, 'skony20', 'Mariusz', 'Skonieczny', '-AaqMQ-qOD7ZkjhMgFIj', '$2y$13$T0tF13zWUL2wgt/T4.6d/egz7aH.FUwIZrCWGiDOHn903yk9ksXDe', 'fZavVNFBOlxih2CBmHRmXLjL9v6xkl', 'skony20@gmail.com', 10, 1448084260, 1453755258, 3),
(13, 'rampiro', NULL, NULL, 'm', '$2y$13$SVf4ul8ggnFCNiz0kje4k..BzS04mzziRe5aqku0wttKkJ7k/VxGy', '12345', 'Skony320@gmail.com', 10, 1453750027, 1453750027, 1),
(15, 'etyertyerty', NULL, NULL, '12312', 'passwordhash', NULL, 'sdsad@gm.pl', 10, 1453750503, 1453750574, 2),
(16, '1234', NULL, NULL, 'MGPq_JVR8NRs9dNU6bB0', '$2y$13$rV2SVjC/6uWIHw/RAzr5b.ViZVYp9FsY1zoSwHRp5tnKc64zfk3Si', 'uk3UXKPWHjOW_rCGA19woqxwefBuPw', 'sdserwad@gm.pl', 10, 1453750694, 1453750794, 1);

--
-- Indeksy dla zrzutów tabel
--

--
-- Indexes for table `category`
--
ALTER TABLE `category`
  ADD PRIMARY KEY (`id`) USING BTREE;

--
-- Indexes for table `comments`
--
ALTER TABLE `comments`
  ADD PRIMARY KEY (`id`) USING BTREE,
  ADD KEY `post_id` (`post_id`);

--
-- Indexes for table `images`
--
ALTER TABLE `images`
  ADD PRIMARY KEY (`id`) USING BTREE,
  ADD KEY `post_id` (`post_id`);

--
-- Indexes for table `post`
--
ALTER TABLE `post`
  ADD PRIMARY KEY (`id`) USING BTREE,
  ADD KEY `data_creation` (`data_creation`),
  ADD KEY `category_id` (`category_id`) USING BTREE;

--
-- Indexes for table `roles`
--
ALTER TABLE `roles`
  ADD PRIMARY KEY (`id`) USING BTREE;

--
-- Indexes for table `user`
--
ALTER TABLE `user`
  ADD PRIMARY KEY (`id`) USING BTREE,
  ADD UNIQUE KEY `username` (`username`),
  ADD UNIQUE KEY `email` (`email`),
  ADD UNIQUE KEY `password_reset_token` (`password_reset_token`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT dla tabeli `category`
--
ALTER TABLE `category`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=6;
--
-- AUTO_INCREMENT dla tabeli `comments`
--
ALTER TABLE `comments`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
--
-- AUTO_INCREMENT dla tabeli `images`
--
ALTER TABLE `images`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
--
-- AUTO_INCREMENT dla tabeli `post`
--
ALTER TABLE `post`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=32;
--
-- AUTO_INCREMENT dla tabeli `roles`
--
ALTER TABLE `roles`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=4;
--
-- AUTO_INCREMENT dla tabeli `user`
--
ALTER TABLE `user`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=17;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
